// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#ifndef _MAIN_INTERFACE_UI_H
#define _MAIN_INTERFACE_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined(LV_LVGL_H_INCLUDE_SIMPLE)
#include "lvgl.h"
#elif defined(__has_include)
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#error "LVGL header not found: expected lvgl.h or lvgl/lvgl.h"
#endif
#else
#include "lvgl/lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_home.h"
#include "screens/ui_apps_menu.h"
#include "screens/ui_clock.h"
#include "screens/ui_manual.h"
#include "screens/ui_set_date.h"
#include "screens/ui_set_time.h"
#include "screens/ui_sd_card_files.h"
#include "screens/ui_settings.h"
#include "screens/ui_wifi.h"
#include "screens/ui_update.h"
#include "screens/ui_tabview.h"
#include "screens/ui_usb_msc.h"
#include "screens/ui_message_box.h"
#include "screens/ui_t9_keyboard.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_message_box_bg_png);
LV_IMG_DECLARE(ui_img_unit_png);
LV_IMG_DECLARE(ui_img_background_h_png);    // assets/background_h.png
LV_IMG_DECLARE(ui_img_storage_status_on_png);    // assets/storage_status_on.png
LV_IMG_DECLARE(ui_img_storage_status_null_png);    // assets/storage_status_null.png
LV_IMG_DECLARE(ui_img_power_gauge_png);    // assets/power_gauge.png
LV_IMG_DECLARE(ui_img_mascot_png);    // assets/mascot.png
LV_IMG_DECLARE(ui_img_navigation_center_png);    // assets/navigation_center.png
LV_IMG_DECLARE(ui_img_background_v_png);    // assets/background_v.png
LV_IMG_DECLARE(ui_img_navigation_edge_png);    // assets/navigation_edge.png
LV_IMG_DECLARE(ui_img_app_01_png);    // assets/app_01.png
LV_IMG_DECLARE(ui_img_app_02_png);    // assets/app_02.png
LV_IMG_DECLARE(ui_img_app_03_png);    // assets/app_03.png
LV_IMG_DECLARE(ui_img_app_04_png);    // assets/app_04.png
LV_IMG_DECLARE(ui_img_app_05_png);    // assets/app_05.png
LV_IMG_DECLARE(ui_img_app_06_png);    // assets/app_06.png
LV_IMG_DECLARE(ui_img_app_07_png);    // assets/app_07.png  (placeholder — replace with SquareLine export)
LV_IMG_DECLARE(ui_img_app_08_png);    // assets/app_08.png
LV_IMG_DECLARE(ui_img_app_09_png);    // assets/app_09.png
LV_IMG_DECLARE(ui_img_pcmontior_png);      // assets/pcmontior.png
/* ── Semantic app icons (SquareLine Studio export) ── */
LV_IMG_DECLARE(ui_img_dino_png);           // App 01 Dino Game
LV_IMG_DECLARE(ui_img_matrix_rain_png);    // App 02 Matrix Rain
LV_IMG_DECLARE(ui_img_vu_meter_png);       // App 03 VU Meter
LV_IMG_DECLARE(ui_img_retro_tv_png);       // App 04 Retro TV
LV_IMG_DECLARE(ui_img_pc_montior_png);     // App 05 PC Monitor (alt spelling)
LV_IMG_DECLARE(ui_img_air_mouse_png);      // App 06 Air Mouse
LV_IMG_DECLARE(ui_img_music_png);          // App 07 Music (hidden)
LV_IMG_DECLARE(ui_img_ble_spam_png);       // App 08 BLE Spam
LV_IMG_DECLARE(ui_img_wifi_killer_png);    // App 09 (stub)
LV_IMG_DECLARE(ui_img_badusb_png);         // App 10 BadUSB
LV_IMG_DECLARE(ui_img_infrared_png);       // App 11 Infrared
LV_IMG_DECLARE(ui_img_nfc_png);            // App 12 (stub)
LV_IMG_DECLARE(ui_img_smarthome_png);      // App 13 (stub)
LV_IMG_DECLARE(ui_img_webserial_png);      // App 14 (stub)
LV_IMG_DECLARE(ui_img_aichat_png);         // App 15 (stub)
LV_IMG_DECLARE(ui_img_clock_bg_png);    // assets/clock bg.png
LV_IMG_DECLARE(ui_img_week_bg_png);    // assets/week bg.png
LV_IMG_DECLARE(ui_img_header_png);    // assets/header.png
LV_IMG_DECLARE(ui_img_border_png);    // assets/border.png
LV_IMG_DECLARE(ui_img_key_prompts_bg_png);    // assets/key prompts bg.png
LV_IMG_DECLARE(ui_img_key_a_png);    // assets/key a.png
LV_IMG_DECLARE(ui_img_key_b_png);    // assets/key b.png
LV_IMG_DECLARE(ui_img_background_png);    // assets/background.png
LV_IMG_DECLARE(ui_img_bar_bg_png);    // assets/bar bg.png
LV_IMG_DECLARE(ui_img_wifi_status_png);    // assets/wifi status.png
LV_IMG_DECLARE(ui_img_button_bg_png);    // assets/button bg.png
LV_IMG_DECLARE(ui_img_detailed_settings_png);    // assets/detailed settings.png
LV_IMG_DECLARE(ui_img_bluetooth_png);    // assets/bluetooth.png
LV_IMG_DECLARE(ui_img_bluetooth_on_png);    // assets/bluetooth_on.png
LV_IMG_DECLARE(ui_img_usb_msc_png);    // assets/usb msc.png
LV_IMG_DECLARE(ui_img_info_png);    // assets/info.png
LV_IMG_DECLARE(ui_img_brightness_icon_png);    // assets/brightness icon.png
LV_IMG_DECLARE(ui_img_volume_icon_png);    // assets/volume icon.png
LV_IMG_DECLARE(ui_img_mascot_update_png);    // assets/mascot update.png
LV_IMG_DECLARE(ui_img_date_png);             // assets/date.png
LV_IMG_DECLARE(ui_img_time_png);             // assets/time.png
LV_IMG_DECLARE(ui_img_mascot_recovery_png);    // assets/mascot recovery.png
LV_IMG_DECLARE(ui_img_mascot_usb_msc_png);    // assets/mascot usb msc.png
LV_IMG_DECLARE(ui_img_slider_png);    // assets/slider.png
LV_IMG_DECLARE(ui_img_mascot_02_png);    // assets/mascot_02.png
LV_IMG_DECLARE(ui_img_alphanumeric_keypad_bg_png);    // assets/alphanumeric_keypad_bg.png
LV_IMG_DECLARE(ui_img_backspace_key_png);    // assets/backspace_key.png
LV_IMG_DECLARE(ui_img_capital_png);    // assets/capital.png
LV_IMG_DECLARE(ui_img_functional_control_keys_bg_png);    // assets/functional_control_keys_bg.png
LV_IMG_DECLARE(ui_img_progress_bar_png);    // assets/progress_bar.png
LV_IMG_DECLARE(ui_img_progress_bg_png);    // assets/progress_bg.png
LV_IMG_DECLARE(ui_img_send_png);    // assets/send.png
LV_IMG_DECLARE(ui_img_switch_png);    // assets/switch.png
LV_IMG_DECLARE(ui_img_t9_bg_png);    // assets/t9_bg.png
LV_IMG_DECLARE(ui_img_text_input_png);    // assets/text_input.png
LV_IMG_DECLARE(ui_img_multi_column_picker_png);    // assets/multi_column_picker.png
LV_IMG_DECLARE(ui_img_788348331);                  // assets/picker_bg (hash-named asset)
LV_IMG_DECLARE(ui_img_picker_time_bg_png);         // assets/picker_time_bg.png
LV_IMG_DECLARE(ui_img_message_box_bg_png);         // assets/message_box_bg.png
LV_IMG_DECLARE(ui_img_pc_monitor_bg_png);    // assets/pc_monitor_bg.png

// FONTS
LV_FONT_DECLARE(ui_font_name_14);
LV_FONT_DECLARE(ui_font_name_24);
LV_FONT_DECLARE(ui_font_number_14);
LV_FONT_DECLARE(ui_font_number_24);
LV_FONT_DECLARE(ui_font_number_60);

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
