// This file was generated by SquareLine Studio, then extended to
// support a 3-column app grid populated from the active app registry.
// LVGL version: 8.3.11

#include "../ui.h"
#include <string.h>

/* ── Widget declarations ─────────────────────────────────────────── */
lv_obj_t * ui_apps_menu;
lv_obj_t * ui_apps_menu_bg;
lv_obj_t * ui_left;
lv_obj_t * ui_app_01;  lv_obj_t * ui_app_02;  lv_obj_t * ui_app_03;
lv_obj_t * ui_app_04;  lv_obj_t * ui_app_05;  lv_obj_t * ui_app_06;
lv_obj_t * ui_app_07;  lv_obj_t * ui_app_08;  lv_obj_t * ui_app_09;
lv_obj_t * ui_name_01; lv_obj_t * ui_name_02; lv_obj_t * ui_name_03;
lv_obj_t * ui_name_04; lv_obj_t * ui_name_05; lv_obj_t * ui_name_06;
lv_obj_t * ui_name_07; lv_obj_t * ui_name_08; lv_obj_t * ui_name_09;

static lv_obj_t * _scroll_cont = NULL;

/* ── Dynamic selection state ─────────────────────────────────────── */
static AppMenuEntry_t s_entries[APPS_MENU_MAX_APPS];
static int            s_entry_count = 0;
static char           s_selected_id[32] = "";

static void on_app_click(lv_event_t * e)
{
    if (lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    int idx = (int)(uintptr_t)lv_event_get_user_data(e);
    if (idx >= 0 && idx < s_entry_count) {
        strncpy(s_selected_id, s_entries[idx].id, sizeof(s_selected_id) - 1);
        s_selected_id[sizeof(s_selected_id) - 1] = '\0';
    }
}

const char * ui_apps_menu_get_selected_id(void)
{
    return s_selected_id[0] ? s_selected_id : NULL;
}

void ui_apps_menu_clear_selected(void)
{
    s_selected_id[0] = '\0';
}

void ui_apps_menu_load_apps(const AppMenuEntry_t * entries, int count)
{
    if (!entries || count <= 0) return;
    if (count > APPS_MENU_MAX_APPS) count = APPS_MENU_MAX_APPS;
    memcpy(s_entries, entries, sizeof(AppMenuEntry_t) * (size_t)count);
    s_entry_count = count;
    s_selected_id[0] = '\0';

    lv_obj_t ** app_ptrs[APPS_MENU_MAX_APPS] = {
        &ui_app_01, &ui_app_02, &ui_app_03, &ui_app_04, &ui_app_05,
        &ui_app_06, &ui_app_07, &ui_app_08, &ui_app_09,
    };
    lv_obj_t ** name_ptrs[APPS_MENU_MAX_APPS] = {
        &ui_name_01, &ui_name_02, &ui_name_03, &ui_name_04, &ui_name_05,
        &ui_name_06, &ui_name_07, &ui_name_08, &ui_name_09,
    };

    for (int i = 0; i < APPS_MENU_MAX_APPS; i++) {
        lv_obj_t * btn = *app_ptrs[i];
        lv_obj_t * lbl = *name_ptrs[i];
        if (!btn || !lbl) continue;
        if (i < count) {
            lv_obj_clear_flag(btn, LV_OBJ_FLAG_HIDDEN);
            lv_obj_clear_flag(lbl, LV_OBJ_FLAG_HIDDEN);
            if (entries[i].icon)
                lv_obj_set_style_bg_img_src(btn, entries[i].icon, LV_PART_MAIN | LV_STATE_DEFAULT);
            lv_label_set_text(lbl, entries[i].name);
        } else {
            lv_obj_add_flag(btn, LV_OBJ_FLAG_HIDDEN);
            lv_obj_add_flag(lbl, LV_OBJ_FLAG_HIDDEN);
        }
    }
}

/* ── App metadata table ──────────────────────────────────────────── */
/* One unique icon per app — replace placeholder .c files with SquareLine exports */
static const struct {
    const lv_img_dsc_t * icon;
    const char *         name;
} _app_info[APPS_MENU_MAX_APPS] = {
    { &ui_img_dino_png,        "Dino"        },
    { &ui_img_matrix_rain_png, "Matrix Rain" },
    { &ui_img_vu_meter_png,    "VU Meter"    },
    { &ui_img_retro_tv_png,    "Retro TV"    },
    { &ui_img_pc_montior_png,  "PC Monitor"  },
    { &ui_img_air_mouse_png,   "Air Mouse"   },
    { &ui_img_ble_spam_png,    "BLE Spam"    },
    { &ui_img_badusb_png,      "BadUSB"      },
    { &ui_img_infrared_png,    "Infrared"    },
};

/* 3 fixed column X positions */
static const lv_coord_t _col_x[3] = { 35, 125, 215 };

/* ── Screen-level event (left swipe → home) ─────────────────────── */

void ui_event_apps_menu(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if (event_code == LV_EVENT_GESTURE &&
        lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_home_screen_init);
    }
}

/* ── Screen init ─────────────────────────────────────────────────── */

void ui_apps_menu_screen_init(void)
{
    ui_apps_menu = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_apps_menu, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_apps_menu_bg = lv_img_create(ui_apps_menu);
    lv_img_set_src(ui_apps_menu_bg, &ui_img_background_v_png);
    lv_obj_set_width(ui_apps_menu_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_apps_menu_bg, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_x(ui_apps_menu_bg, 0);
    lv_obj_set_y(ui_apps_menu_bg, -1);
    lv_obj_set_align(ui_apps_menu_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_apps_menu_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_apps_menu_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_left = lv_img_create(ui_apps_menu);
    lv_img_set_src(ui_left, &ui_img_navigation_edge_png);
    lv_obj_set_width(ui_left, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_left, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_left, 10);
    lv_obj_set_y(ui_left, 204);
    lv_obj_add_flag(ui_left, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_left, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_angle(ui_left, -900);

    /* Transparent full-screen scrollable container for the app grid.
     * Background/navigation edge below show through the transparent bg. */
    _scroll_cont = lv_obj_create(ui_apps_menu);
    lv_obj_set_pos(_scroll_cont, 0, 0);
    lv_obj_set_size(_scroll_cont, 320, 240);
    lv_obj_set_style_bg_opa(_scroll_cont,     LV_OPA_TRANSP, 0);
    lv_obj_set_style_border_width(_scroll_cont, 0, 0);
    lv_obj_set_style_pad_all(_scroll_cont,    0, 0);
    lv_obj_set_style_radius(_scroll_cont,     0, 0);
    lv_obj_set_scroll_dir(_scroll_cont, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(_scroll_cont, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_style_bg_color(_scroll_cont, lv_color_hex(0xBBE700),
                               LV_PART_SCROLLBAR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(_scroll_cont, 255,
                             LV_PART_SCROLLBAR | LV_STATE_DEFAULT);

    /* Pointer arrays map loop index → named global variable */
    lv_obj_t ** app_ptrs[APPS_MENU_MAX_APPS] = {
        &ui_app_01, &ui_app_02, &ui_app_03, &ui_app_04, &ui_app_05,
        &ui_app_06, &ui_app_07, &ui_app_08, &ui_app_09,
    };
    lv_obj_t ** name_ptrs[APPS_MENU_MAX_APPS] = {
        &ui_name_01, &ui_name_02, &ui_name_03, &ui_name_04, &ui_name_05,
        &ui_name_06, &ui_name_07, &ui_name_08, &ui_name_09,
    };

    for (int i = 0; i < APPS_MENU_MAX_APPS; i++) {
        int        col = i % 3;
        int        row = i / 3;
        lv_coord_t bx  = _col_x[col];
        lv_coord_t by  = (lv_coord_t)(30 + row * 105);

        lv_obj_t * btn = lv_btn_create(_scroll_cont);
        lv_obj_set_width(btn, 70);
        lv_obj_set_height(btn, 70);
        lv_obj_set_x(btn, bx);
        lv_obj_set_y(btn, by);
        lv_obj_add_flag(btn, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
        lv_obj_clear_flag(btn, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
        lv_obj_set_style_radius(btn, 35, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_color(btn, lv_color_hex(0xBEE700), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_opa(btn, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_bg_img_src(btn, _app_info[i].icon, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_color(btn, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_shadow_opa(btn, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_outline_color(btn, lv_color_hex(0x9DDE00), LV_PART_MAIN | LV_STATE_PRESSED);
        lv_obj_set_style_outline_opa(btn, 255, LV_PART_MAIN | LV_STATE_PRESSED);
        lv_obj_set_style_outline_width(btn, 10, LV_PART_MAIN | LV_STATE_PRESSED);
        lv_obj_set_style_outline_pad(btn, 0, LV_PART_MAIN | LV_STATE_PRESSED);
        lv_obj_set_style_border_width(btn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
        lv_obj_set_style_outline_width(btn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
        lv_obj_set_style_outline_pad(btn, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
        lv_obj_add_event_cb(btn, on_app_click, LV_EVENT_CLICKED, (void *)(uintptr_t)i);
        *app_ptrs[i] = btn;

        lv_obj_t * lbl = lv_label_create(_scroll_cont);
        lv_obj_set_width(lbl, LV_SIZE_CONTENT);
        lv_obj_set_height(lbl, LV_SIZE_CONTENT);
        lv_label_set_text(lbl, _app_info[i].name);
        lv_obj_set_style_text_color(lbl, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_opa(lbl, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
        lv_obj_set_style_text_font(lbl, &ui_font_name_14, LV_PART_MAIN | LV_STATE_DEFAULT);
        /* Center label horizontally below button */
        lv_obj_align_to(lbl, btn, LV_ALIGN_OUT_BOTTOM_MID, 0, 5);
        *name_ptrs[i] = lbl;
    }

    lv_obj_add_event_cb(ui_apps_menu, ui_event_apps_menu, LV_EVENT_ALL, NULL);
}

/* ── Screen destroy ──────────────────────────────────────────────── */

void ui_apps_menu_screen_destroy(void)
{
    if (ui_apps_menu) lv_obj_del(ui_apps_menu);

    ui_apps_menu    = NULL;
    ui_apps_menu_bg = NULL;
    ui_left         = NULL;
    _scroll_cont    = NULL;
    ui_app_01  = NULL; ui_app_02  = NULL; ui_app_03  = NULL;
    ui_app_04  = NULL; ui_app_05  = NULL; ui_app_06  = NULL;
    ui_app_07  = NULL; ui_app_08  = NULL; ui_app_09  = NULL;
    ui_name_01 = NULL; ui_name_02 = NULL; ui_name_03 = NULL;
    ui_name_04 = NULL; ui_name_05 = NULL; ui_name_06 = NULL;
    ui_name_07 = NULL; ui_name_08 = NULL; ui_name_09 = NULL;
}
