// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "../ui.h"
#include "../ui_wifi_bridge.h"
#include "../ui_sd_bridge.h"
#include "../../system/usb_msc.h"
#include "../../system/usb_manager.h"
#include "../../system/settings_bridge.h"

static lv_obj_t   * s_wifi_lbl          = NULL;
static lv_obj_t   * s_wifi_dot          = NULL;
static lv_timer_t * s_wifi_lbl_timer    = NULL;

lv_obj_t * ui_settings;
lv_obj_t * ui_settings_bg;
lv_obj_t * ui_brightness_bar_bg;
lv_obj_t * ui_volume_bar_bg;
lv_obj_t * ui_wifi_status;
lv_obj_t * ui_settings_button_bg;
lv_obj_t * ui_settings_button;
lv_obj_t * ui_ble_button;
lv_obj_t * ui_msc_button;
lv_obj_t * ui_info_button;
lv_obj_t * ui_bar_brightness_icon;
lv_obj_t * ui_bar_volume_icon;
lv_obj_t * ui_brightness_slider;
lv_obj_t * ui_volume_slider;
lv_obj_t * ui_navigation_right;

static void ui_event_wifi_status_click(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    _ui_screen_change(&ui_wifi, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_wifi_screen_init);
}

static void ui_event_settings_button_click(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    _ui_screen_change(&ui_tabview, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_tabview_screen_init);
}

static void ui_event_msc_button_click(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;

    /* Guard: SD card must be present before enabling MSC.
     * Without a card the host would enumerate an empty drive and MSC init
     * may panic the SD driver when it tries to read the block count. */
    if (!ui_sd_present()) {
        _ui_screen_change(&ui_usb_msc, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_usb_msc_screen_init);
        if(ui_usb_msc_label) lv_label_set_text(ui_usb_msc_label, "no SD card — insert and retry");
        return;
    }

    /* Enable MSC first so the host sees the drive immediately after screen
     * transition completes. Disable is handled by launcher A/B key handlers. */
    int ok = usb_manager_request(USB_MODE_MSC);
    _ui_screen_change(&ui_usb_msc, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_usb_msc_screen_init);
    if(ui_usb_msc_label) {
        lv_label_set_text(ui_usb_msc_label, ok ? "connected - copy files" : "MSC init failed");
    }
}

// ── NVS persist callbacks ─────────────────────────────────────────────────

static void brightness_slider_cb(lv_event_t * e)
{
    settings_set_brightness((int)lv_slider_get_value(lv_event_get_target(e)));
}

static void volume_slider_cb(lv_event_t * e)
{
    settings_set_volume((int)lv_slider_get_value(lv_event_get_target(e)));
}

static void ble_btn_cb(lv_event_t * e)
{
    settings_set_ble_en(lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED) ? 1 : 0);
}

// event funtions
void ui_event_settings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_get_act());
        _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_home_screen_init);
    }
}

// ── WiFi label refresh (2 s) ──────────────────────────────────────────────
static void _wifi_lbl_refresh(lv_timer_t * t)
{
    (void)t;
    if(!s_wifi_lbl) return;
    wifi_bridge_status_t st = ui_wifi_bridge_get_status();
    char buf[80];
    if(st == WIFI_BRIDGE_CONNECTED) {
        if(s_wifi_dot) lv_obj_clear_flag(s_wifi_dot, LV_OBJ_FLAG_HIDDEN);
        lv_snprintf(buf, sizeof(buf), "connect: %s", ui_wifi_bridge_get_current_ssid());
    } else {
        if(s_wifi_dot) lv_obj_add_flag(s_wifi_dot, LV_OBJ_FLAG_HIDDEN);
        ui_wifi_bridge_get_status_text(buf, sizeof(buf));
    }
    lv_label_set_text(s_wifi_lbl, buf);
}

// build funtions

void ui_settings_screen_init(void)
{
    ui_settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_settings, lv_color_black(), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings, LV_OPA_COVER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_settings_bg = lv_img_create(ui_settings);
    lv_img_set_src(ui_settings_bg, &ui_img_background_png);
    lv_obj_set_width(ui_settings_bg, LV_SIZE_CONTENT);   /// 320
    lv_obj_set_height(ui_settings_bg, LV_SIZE_CONTENT);    /// 241
    lv_obj_set_align(ui_settings_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_settings_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_settings_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_brightness_bar_bg = lv_img_create(ui_settings);
    lv_img_set_src(ui_brightness_bar_bg, &ui_img_bar_bg_png);
    lv_obj_set_width(ui_brightness_bar_bg, LV_SIZE_CONTENT);   /// 77
    lv_obj_set_height(ui_brightness_bar_bg, LV_SIZE_CONTENT);    /// 202
    lv_obj_set_x(ui_brightness_bar_bg, 23);
    lv_obj_set_y(ui_brightness_bar_bg, 18);
    lv_obj_add_flag(ui_brightness_bar_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_brightness_bar_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_volume_bar_bg = lv_img_create(ui_settings);
    lv_img_set_src(ui_volume_bar_bg, &ui_img_bar_bg_png);
    lv_obj_set_width(ui_volume_bar_bg, LV_SIZE_CONTENT);   /// 77
    lv_obj_set_height(ui_volume_bar_bg, LV_SIZE_CONTENT);    /// 202
    lv_obj_set_x(ui_volume_bar_bg, 81);
    lv_obj_set_y(ui_volume_bar_bg, 18);
    lv_obj_add_flag(ui_volume_bar_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_volume_bar_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    // Middle layer: Sliders - interactive white line bars (z-order: bars < sliders < icons)
    ui_brightness_slider = lv_slider_create(ui_settings);
    lv_obj_set_width(ui_brightness_slider, 39);
    lv_obj_set_height(ui_brightness_slider, 163);
    lv_obj_set_x(ui_brightness_slider, 42);
    lv_obj_set_y(ui_brightness_slider, 36);
    lv_slider_set_range(ui_brightness_slider, 0, 100);
    lv_slider_set_value(ui_brightness_slider, 50, LV_ANIM_OFF);
    // MAIN part style - transparent body
    lv_obj_set_style_bg_opa(ui_brightness_slider, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_brightness_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_brightness_slider, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    // INDICATOR part style - white, fully opaque
    lv_obj_set_style_bg_color(ui_brightness_slider, lv_color_white(), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_brightness_slider, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_brightness_slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // KNOB part style - transparent (no visible knob)
    lv_obj_set_style_bg_opa(ui_brightness_slider, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_brightness_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_brightness_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_volume_slider = lv_slider_create(ui_settings);
    lv_obj_set_width(ui_volume_slider, 39);
    lv_obj_set_height(ui_volume_slider, 163);
    lv_obj_set_x(ui_volume_slider, 100);
    lv_obj_set_y(ui_volume_slider, 36);
    lv_slider_set_range(ui_volume_slider, 0, 100);
    lv_slider_set_value(ui_volume_slider, 50, LV_ANIM_OFF);
    // MAIN part style - transparent body
    lv_obj_set_style_bg_opa(ui_volume_slider, LV_OPA_TRANSP, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_volume_slider, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_volume_slider, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    // INDICATOR part style - white, fully opaque
    lv_obj_set_style_bg_color(ui_volume_slider, lv_color_white(), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_volume_slider, LV_OPA_COVER, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_volume_slider, 0, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    // KNOB part style - transparent (no visible knob)
    lv_obj_set_style_bg_opa(ui_volume_slider, LV_OPA_TRANSP, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_volume_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(ui_volume_slider, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_wifi_status = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_wifi_status, 155);
    lv_obj_set_height(ui_wifi_status, 80);
    lv_obj_set_x(ui_wifi_status, 142);
    lv_obj_set_y(ui_wifi_status, 19);
    lv_obj_add_flag(ui_wifi_status, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_wifi_status, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_clear_flag(ui_wifi_status, LV_OBJ_FLAG_OVERFLOW_VISIBLE); /// Keep marquee text inside the card
    lv_obj_set_style_radius(ui_wifi_status, 18, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_wifi_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_wifi_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_wifi_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_wifi_status, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_wifi_status, &ui_img_wifi_status_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_add_event_cb(ui_wifi_status, ui_event_wifi_status_click, LV_EVENT_CLICKED, NULL);


    s_wifi_lbl = lv_label_create(ui_wifi_status);
    lv_obj_set_size(s_wifi_lbl, 106, 40);
    lv_obj_set_pos(s_wifi_lbl, 42, 23);
    lv_label_set_long_mode(s_wifi_lbl, LV_LABEL_LONG_SCROLL_CIRCULAR);
    lv_obj_set_style_text_color(s_wifi_lbl, lv_color_hex(0xFFFFFF), 0);
    lv_obj_set_style_text_font(s_wifi_lbl, &ui_font_name_14, 0);
    lv_obj_set_style_anim_speed(s_wifi_lbl, 30, 0);
    lv_label_set_text(s_wifi_lbl, "");
    _wifi_lbl_refresh(NULL);
    s_wifi_lbl_timer = lv_timer_create(_wifi_lbl_refresh, 2000, NULL);

    ui_settings_button_bg = lv_img_create(ui_settings);
    lv_img_set_src(ui_settings_button_bg, &ui_img_button_bg_png);
    lv_obj_set_width(ui_settings_button_bg, LV_SIZE_CONTENT);   /// 154
    lv_obj_set_height(ui_settings_button_bg, LV_SIZE_CONTENT);    /// 193
    lv_obj_set_x(ui_settings_button_bg, 141);
    lv_obj_set_y(ui_settings_button_bg, 52);
    lv_obj_add_flag(ui_settings_button_bg, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_settings_button_bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_settings_button = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_settings_button, 42);
    lv_obj_set_height(ui_settings_button, 43);
    lv_obj_set_x(ui_settings_button, 172);
    lv_obj_set_y(ui_settings_button, 100);
    lv_obj_add_flag(ui_settings_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_settings_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_settings_button, 43, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_settings_button, lv_color_hex(0xBEE700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_settings_button, &ui_img_detailed_settings_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_settings_button, lv_color_hex(0x9DDE00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_settings_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_ble_button = lv_imgbtn_create(ui_settings);
    lv_imgbtn_set_src(ui_ble_button, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bluetooth_png, NULL);
    lv_imgbtn_set_src(ui_ble_button, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bluetooth_png, NULL);
    lv_imgbtn_set_src(ui_ble_button, LV_IMGBTN_STATE_DISABLED, NULL, &ui_img_bluetooth_png, NULL);
    lv_imgbtn_set_src(ui_ble_button, LV_IMGBTN_STATE_CHECKED_PRESSED, NULL, &ui_img_bluetooth_on_png, NULL);
    lv_imgbtn_set_src(ui_ble_button, LV_IMGBTN_STATE_CHECKED_RELEASED, NULL, &ui_img_bluetooth_on_png, NULL);
    lv_imgbtn_set_src(ui_ble_button, LV_IMGBTN_STATE_CHECKED_DISABLED, NULL, &ui_img_bluetooth_on_png, NULL);
    lv_obj_set_width(ui_ble_button, 42);
    lv_obj_set_height(ui_ble_button, 43);
    lv_obj_set_x(ui_ble_button, 172);
    lv_obj_set_y(ui_ble_button, 149);
    lv_obj_add_flag(ui_ble_button, LV_OBJ_FLAG_CHECKABLE);
    lv_obj_add_flag(ui_ble_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);
    lv_obj_clear_flag(ui_ble_button, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_img_src(ui_ble_button, &ui_img_bluetooth_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_msc_button = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_msc_button, 42);
    lv_obj_set_height(ui_msc_button, 43);
    lv_obj_set_x(ui_msc_button, 224);
    lv_obj_set_y(ui_msc_button, 100);
    lv_obj_add_flag(ui_msc_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_msc_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_msc_button, 43, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_msc_button, lv_color_hex(0xBEE700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_msc_button, &ui_img_usb_msc_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_msc_button, lv_color_hex(0x9DDE00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_msc_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    ui_info_button = lv_btn_create(ui_settings);
    lv_obj_set_width(ui_info_button, 42);
    lv_obj_set_height(ui_info_button, 43);
    lv_obj_set_x(ui_info_button, 224);
    lv_obj_set_y(ui_info_button, 149);
    lv_obj_add_flag(ui_info_button, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_info_button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_info_button, 43, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_info_button, lv_color_hex(0xBEE700), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_info_button, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_info_button, &ui_img_info_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_info_button, lv_color_hex(0x9DDE00), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_opa(ui_info_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_width(ui_info_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_outline_pad(ui_info_button, 0, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_width(ui_info_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_width(ui_info_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_outline_pad(ui_info_button, 0, LV_PART_MAIN | LV_STATE_FOCUSED);

    // Foreground layer: Icons (z-order: bars < sliders < icons)
    ui_bar_brightness_icon = lv_img_create(ui_settings);
    lv_img_set_src(ui_bar_brightness_icon, &ui_img_brightness_icon_png);
    lv_obj_set_width(ui_bar_brightness_icon, LV_SIZE_CONTENT);   /// 27
    lv_obj_set_height(ui_bar_brightness_icon, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_bar_brightness_icon, 107);
    lv_obj_set_y(ui_bar_brightness_icon, 164);
    lv_obj_add_flag(ui_bar_brightness_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bar_brightness_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_bar_volume_icon = lv_img_create(ui_settings);
    lv_img_set_src(ui_bar_volume_icon, &ui_img_volume_icon_png);
    lv_obj_set_width(ui_bar_volume_icon, LV_SIZE_CONTENT);   /// 28
    lv_obj_set_height(ui_bar_volume_icon, LV_SIZE_CONTENT);    /// 28
    lv_obj_set_x(ui_bar_volume_icon, 48);
    lv_obj_set_y(ui_bar_volume_icon, 164);
    lv_obj_add_flag(ui_bar_volume_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_bar_volume_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_navigation_right = lv_img_create(ui_settings);
    lv_img_set_src(ui_navigation_right, &ui_img_navigation_edge_png);
    lv_obj_set_width(ui_navigation_right, LV_SIZE_CONTENT);   /// 26
    lv_obj_set_height(ui_navigation_right, LV_SIZE_CONTENT);    /// 27
    lv_obj_set_x(ui_navigation_right, 10);
    lv_obj_set_y(ui_navigation_right, 204);
    lv_img_set_angle(ui_navigation_right, 900);
    lv_obj_add_flag(ui_navigation_right, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_navigation_right, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_add_event_cb(ui_settings, ui_event_settings, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_settings_button, ui_event_settings_button_click, LV_EVENT_CLICKED, NULL);
    lv_obj_add_event_cb(ui_msc_button, ui_event_msc_button_click, LV_EVENT_CLICKED, NULL);

    /* 左栏(ui_brightness_slider, x=42)=音量（正向）
     * 右栏(ui_volume_slider, x=100)=亮度（正向：top=最亮） */
    lv_slider_set_value(ui_brightness_slider, sys_get_volume(),       LV_ANIM_OFF);
    lv_slider_set_value(ui_volume_slider,     sys_get_brightness(),   LV_ANIM_OFF);
    if(settings_get_ble_en()) lv_obj_add_state(ui_ble_button, LV_STATE_CHECKED);

    /* Wire persist callbacks */
    lv_obj_add_event_cb(ui_brightness_slider, volume_slider_cb,     LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_volume_slider,     brightness_slider_cb, LV_EVENT_VALUE_CHANGED, NULL);
    lv_obj_add_event_cb(ui_ble_button,        ble_btn_cb,           LV_EVENT_VALUE_CHANGED, NULL);
}

void ui_settings_screen_destroy(void)
{
    if(s_wifi_lbl_timer) { lv_timer_del(s_wifi_lbl_timer); s_wifi_lbl_timer = NULL; }
    s_wifi_lbl = NULL;
    s_wifi_dot = NULL;
    if(ui_settings) lv_obj_del(ui_settings);

    // NULL screen variables
    ui_settings = NULL;
    ui_settings_bg = NULL;
    ui_brightness_bar_bg = NULL;
    ui_volume_bar_bg = NULL;
    ui_wifi_status = NULL;
    ui_settings_button_bg = NULL;
    ui_settings_button = NULL;
    ui_ble_button = NULL;
    ui_msc_button = NULL;
    ui_info_button = NULL;
    ui_bar_brightness_icon = NULL;
    ui_bar_volume_icon = NULL;
    ui_brightness_slider = NULL;
    ui_volume_slider = NULL;
    ui_navigation_right = NULL;

}
