// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.2
// LVGL version: 8.3.11
// Project name: main_interface

#include "../ui.h"
#include "../ui_sd_bridge.h"
#include "../ui_wifi_bridge.h"
#include "../../system/settings_bridge.h"
#include "../../system/persist.h"
#include <time.h>
#include <esp_system.h>
#include "../../system/recovery.h"
#include "../../system/power_mgmt.h"
#include "../../ui/screens/ui_set_date.h"
#include "../../ui/screens/ui_set_time.h"
#include <nvs.h>

// ── Color palette ─────────────────────────────────────────────────────────
#define TV_BG      0x0A0B09
#define TV_LIME    0xC4EE1F
#define TV_INK     0x14180C
#define TV_TEXT    0xE9EFE2
#define TV_MUTED   0x9AA394
#define TV_TRACK   0x2A2D26
#define TV_DANGER  0xFF5A4D
#define TV_CARD    0x141713
#define TV_ORANGE  0xF5A623

// ── Layout constants ──────────────────────────────────────────────────────
#define TAB_BAR_W  74
#define TAB_PG_W   (320 - TAB_BAR_W)          // 246px content panel
#define TAB_MARG   8
#define TAB_USE_W  (TAB_PG_W - 2 * TAB_MARG)  // 230px usable width
#define TAB_SW_X   (TAB_PG_W - TAB_MARG - 42) // right-align 42px switch (=196)

#define CARD_PAD   8
#define CARD_INN   (TAB_USE_W - 2 * CARD_PAD)  // 214px card inner width

// ── Screen objects ────────────────────────────────────────────────────────
lv_obj_t * ui_tabview;
lv_obj_t * ui_tabview_settings;
lv_obj_t * ui_TabPage1;
lv_obj_t * ui_TabPage2;
lv_obj_t * ui_TabPage3;
lv_obj_t * ui_TabPage4;
lv_obj_t * ui_TabPage5;
lv_obj_t * ui_tab_key_prompts_bg;
lv_obj_t * ui_tab_key_a_bg;
lv_obj_t * ui_tab_key_b_bg;
lv_obj_t * ui_tab_key_a_save;
lv_obj_t * ui_tab_key_a_back;

static lv_obj_t  * s_lbl_date     = NULL;
static lv_obj_t  * s_lbl_time_str = NULL;
static lv_timer_t * s_time_timer  = NULL;

/* ── System tab: battery live data ──────────────────────────────── */
static lv_obj_t  * s_sys_bat_pct_lbl = NULL;
static lv_obj_t  * s_sys_bat_status  = NULL;
static lv_obj_t  * s_sys_bat_fill    = NULL;
static lv_timer_t * s_sys_bat_timer  = NULL;

// ── Callbacks ─────────────────────────────────────────────────────────────

static void slider_pct_cb(lv_event_t * e)
{
    lv_obj_t * sl  = lv_event_get_target(e);
    lv_obj_t * lbl = (lv_obj_t *)lv_event_get_user_data(e);
    if(lbl) lv_label_set_text_fmt(lbl, "%d%%", (int)lv_slider_get_value(sl));
}

static void _sys_bat_refresh(lv_timer_t * t)
{
    (void)t;
    if (!s_sys_bat_pct_lbl || !s_sys_bat_status || !s_sys_bat_fill) return;

    int  pct      = power_battery_pct();
    bool charging = power_is_charging();

    char buf[8];
    lv_snprintf(buf, sizeof(buf), "%d%%", pct);
    lv_label_set_text(s_sys_bat_pct_lbl, buf);

    lv_obj_set_style_text_color(s_sys_bat_pct_lbl, lv_color_white(), 0);
    lv_label_set_text(s_sys_bat_status, charging ? "charging" : "discharging");

    uint32_t bar_clr = charging                    ? 0x00CC00u
                     : (pct <= POWER_CRIT_BAT_PCT) ? TV_DANGER
                     : (pct <= POWER_WARN_BAT_PCT) ? TV_ORANGE
                     :                               TV_LIME;
    int fw = pct * 36 / 100;
    if (fw < 1) fw = 1;
    lv_obj_set_width(s_sys_bat_fill, fw);
    lv_obj_set_style_bg_color(s_sys_bat_fill, lv_color_hex(bar_clr), 0);
}

static void tab_time_refresh(lv_timer_t * t)
{
    (void)t;
    if(!s_lbl_date || !s_lbl_time_str) return;
    time_t now = time(NULL);
    struct tm * ti = localtime(&now);
    if(!ti) return;
    static const char * const wd[7] = {"Sun","Mon","Tue","Wed","Thu","Fri","Sat"};
    lv_label_set_text_fmt(s_lbl_date,     "%02d / %02d / %04d",
                          ti->tm_mon + 1, ti->tm_mday, ti->tm_year + 1900);
    lv_label_set_text_fmt(s_lbl_time_str, "%s  %02d:%02d",
                          wd[ti->tm_wday], ti->tm_hour, ti->tm_min);
}

static void tab_key_a_cb(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    _ui_screen_change(&ui_home, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_home_screen_init);
}

static void tab_key_b_cb(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    _ui_screen_change(&ui_settings, LV_SCR_LOAD_ANIM_FADE_ON, 350, 0, &ui_settings_screen_init);
}

static void tab_reboot_cb(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    esp_restart();
}

static void _fr_msgbox_cb(lv_event_t * e)
{
    lv_obj_t * mbox = lv_event_get_current_target(e);
    /* Button index 0 = "Reset", 1 = "Cancel" */
    if (lv_msgbox_get_active_btn(mbox) == 0) {
        lv_msgbox_close(mbox);
        recovery_factory_reset();   /* erase NVS + restart — does not return */
    } else {
        lv_msgbox_close(mbox);
    }
}

static void tab_factory_reset_cb(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    static const char * btns[] = {"Reset", "Cancel", ""};
    lv_obj_t * mbox = lv_msgbox_create(lv_scr_act(),
        "Factory Reset",
        "Erase ALL settings?\nThis cannot be undone.",
        btns, false);
    lv_obj_set_style_bg_color(mbox,    lv_color_hex(TV_CARD),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(mbox, lv_color_hex(TV_DANGER), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(mbox, 2,                      LV_PART_MAIN | LV_STATE_DEFAULT);
    /* Sans ceci, titre et message héritent du gris sombre du thème par défaut,
     * illisible sur le fond TV_CARD : seuls les boutons ressortaient. Les
     * propriétés de texte étant héritées, la régler sur la boîte suffit. */
    lv_obj_set_style_text_color(mbox, lv_color_hex(TV_TEXT), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_center(mbox);
    lv_obj_add_event_cb(mbox, _fr_msgbox_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

// ── NVS persist callbacks — called on LV_EVENT_VALUE_CHANGED ─────────────

static void tab_bright_cb(lv_event_t * e)
{
    settings_set_brightness((int)lv_slider_get_value(lv_event_get_target(e)));
}

static void tab_led_cb(lv_event_t * e)
{
    settings_set_led_bright((int)lv_slider_get_value(lv_event_get_target(e)));
}

static void tab_vol_cb(lv_event_t * e)
{
    settings_set_volume((int)lv_slider_get_value(lv_event_get_target(e)));
}

static void tab_key_snd_cb(lv_event_t * e)
{
    settings_set_key_sound(lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED) ? 1 : 0);
}

static void tab_ble_sw_cb(lv_event_t * e)
{
    settings_set_ble_en(lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED) ? 1 : 0);
}

static void tab_wifi_sw_cb(lv_event_t * e)
{
    settings_set_wifi_en(lv_obj_has_state(lv_event_get_target(e), LV_STATE_CHECKED) ? 1 : 0);
}

// ── Widget helpers ────────────────────────────────────────────────────────

static void style_tab_page(lv_obj_t * page)
{
    lv_obj_set_style_bg_color(page,    lv_color_hex(TV_BG), 0);
    lv_obj_set_style_bg_opa(page,      LV_OPA_COVER, 0);
    lv_obj_set_style_pad_all(page,     0, 0);
    lv_obj_set_style_pad_bottom(page,  40, 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_style_shadow_width(page, 0, 0);
    lv_obj_set_style_outline_width(page, 0, 0);
    lv_obj_set_scroll_dir(page,        LV_DIR_VER);
    lv_obj_set_scrollbar_mode(page,    LV_SCROLLBAR_MODE_AUTO);
}

static lv_obj_t * mk_lbl(lv_obj_t * p, const char * text,
                          lv_coord_t x, lv_coord_t y,
                          uint32_t color, const lv_font_t * font)
{
    lv_obj_t * lbl = lv_label_create(p);
    lv_label_set_text(lbl, text);
    lv_obj_set_pos(lbl, x, y);
    lv_obj_set_style_text_color(lbl, lv_color_hex(color), 0);
    lv_obj_set_style_text_font(lbl, font, 0);
    return lbl;
}

// Right-aligned label: x=0, width fills to right edge with TAB_MARG gap
static lv_obj_t * mk_lbl_r(lv_obj_t * p, const char * text,
                             lv_coord_t y, uint32_t color, const lv_font_t * font)
{
    lv_obj_t * lbl = lv_label_create(p);
    lv_label_set_text(lbl, text);
    lv_obj_set_pos(lbl, 0, y);
    lv_obj_set_width(lbl, TAB_PG_W - TAB_MARG);
    lv_obj_set_style_text_align(lbl, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(color), 0);
    lv_obj_set_style_text_font(lbl, font, 0);
    return lbl;
}

// Right-aligned label inside a card (full CARD_INN width)
static lv_obj_t * mk_lbl_r_card(lv_obj_t * card, const char * text,
                                  lv_coord_t y, uint32_t color, const lv_font_t * font)
{
    lv_obj_t * lbl = lv_label_create(card);
    lv_label_set_text(lbl, text);
    lv_obj_set_pos(lbl, 0, y);
    lv_obj_set_width(lbl, CARD_INN);
    lv_obj_set_style_text_align(lbl, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(lbl, lv_color_hex(color), 0);
    lv_obj_set_style_text_font(lbl, font, 0);
    return lbl;
}

// Slider: half-height (14px), white knob with lime border (matches first screenshot)
static lv_obj_t * mk_slider(lv_obj_t * p, lv_coord_t y,
                             int value, lv_obj_t * val_lbl)
{
    lv_obj_t * sl = lv_slider_create(p);
    lv_obj_set_size(sl, TAB_USE_W, 14);
    lv_obj_set_pos(sl, TAB_MARG, y);
    lv_slider_set_range(sl, 0, 100);
    lv_slider_set_value(sl, value, LV_ANIM_OFF);

    // Track (unfilled)
    lv_obj_set_style_bg_color(sl, lv_color_hex(TV_TRACK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sl,   LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sl,   LV_RADIUS_CIRCLE,       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sl, 0,                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(sl, 0,                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(sl,  0,                       LV_PART_MAIN | LV_STATE_DEFAULT);

    // Indicator (filled, lime)
    lv_obj_set_style_bg_color(sl, lv_color_hex(TV_LIME),  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sl,   LV_OPA_COVER,           LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sl,   LV_RADIUS_CIRCLE,       LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Knob: white circle with lime border — matches screenshot 1
    lv_obj_set_style_bg_color(sl, lv_color_hex(0xFFFFFF),  LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sl,   LV_OPA_COVER,            LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sl,   LV_RADIUS_CIRCLE,        LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sl, lv_color_hex(TV_LIME), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sl, 2,                    LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sl,   LV_OPA_COVER,        LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(sl,  4,                        LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(sl, 0,                   LV_PART_KNOB | LV_STATE_DEFAULT);

    if(val_lbl) lv_obj_add_event_cb(sl, slider_pct_cb, LV_EVENT_VALUE_CHANGED, val_lbl);
    return sl;
}

// Switch: matches ui_wifi_scan_switch style (42×22, dark track, white border, lime on)
static lv_obj_t * mk_switch(lv_obj_t * p, lv_coord_t y, bool checked)
{
    lv_obj_t * sw = lv_switch_create(p);
    lv_obj_set_size(sw, 42, 22);
    lv_obj_set_pos(sw, TAB_SW_X, y);

    // Track (OFF state)
    lv_obj_set_style_bg_color(sw, lv_color_hex(0x3D414A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sw,   LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sw,   LV_RADIUS_CIRCLE,       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sw, 2,                       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sw,   LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_DEFAULT);

    // Track (ON/CHECKED state — border stays white)
    lv_obj_set_style_border_color(sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(sw, 2,                       LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(sw,   LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_outline_width(sw, 0,                      LV_PART_MAIN | LV_STATE_FOCUSED);

    // Indicator (the lime fill, visible when checked)
    lv_obj_set_style_bg_color(sw, lv_color_hex(0xC4F000),     LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(sw,   LV_OPA_COVER,               LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_radius(sw,   LV_RADIUS_CIRCLE,           LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(sw, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(sw, 2,                       LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(sw,   LV_OPA_COVER,           LV_PART_INDICATOR | LV_STATE_CHECKED);

    // Knob (white pill)
    lv_obj_set_style_bg_color(sw, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sw,   LV_OPA_COVER,           LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sw,   LV_RADIUS_CIRCLE,       LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sw, 0,                   LV_PART_KNOB | LV_STATE_DEFAULT);

    if(checked) lv_obj_add_state(sw, LV_STATE_CHECKED);
    return sw;
}

// Switch inside a card at explicit (x, y) coords — same 42×22 size as mk_switch
static lv_obj_t * mk_card_switch(lv_obj_t * card, lv_coord_t x, lv_coord_t y, bool checked)
{
    lv_obj_t * sw = lv_switch_create(card);
    lv_obj_set_size(sw, 42, 22);
    lv_obj_set_pos(sw, x, y);

    lv_obj_set_style_bg_color(sw, lv_color_hex(0x3D414A), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sw,   LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sw,   LV_RADIUS_CIRCLE,       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sw, 2,                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sw,  LV_OPA_COVER,         LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(sw, 0,                  LV_PART_MAIN | LV_STATE_FOCUSED);

    lv_obj_set_style_border_color(sw, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(sw, 2,                   LV_PART_MAIN | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(sw,  LV_OPA_COVER,         LV_PART_MAIN | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(sw, lv_color_hex(TV_LIME), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(sw,   LV_OPA_COVER,          LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_radius(sw,   LV_RADIUS_CIRCLE,      LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_color(sw, lv_color_hex(0xFFFFFF), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(sw, 2,                  LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_border_opa(sw,  LV_OPA_COVER,       LV_PART_INDICATOR | LV_STATE_CHECKED);

    lv_obj_set_style_bg_color(sw, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sw,   LV_OPA_COVER,           LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sw,   LV_RADIUS_CIRCLE,       LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sw, 0,                   LV_PART_KNOB | LV_STATE_DEFAULT);

    if(checked) lv_obj_add_state(sw, LV_STATE_CHECKED);
    return sw;
}

// Display tab slider: large glowing knob matching reference screenshot
// track h=16, knob protrudes 10px per side → knob ⌀ 36px, with lime glow
static lv_obj_t * mk_display_slider(lv_obj_t * card, lv_coord_t y,
                                     int value, lv_obj_t * val_lbl)
{
    lv_obj_t * sl = lv_slider_create(card);
    lv_obj_set_size(sl, CARD_INN, 16);
    lv_obj_set_pos(sl, 0, y);
    lv_slider_set_range(sl, 0, 100);
    lv_slider_set_value(sl, value, LV_ANIM_OFF);

    // Track (unfilled, dark)
    lv_obj_set_style_bg_color(sl, lv_color_hex(TV_TRACK), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sl,   LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sl,   LV_RADIUS_CIRCLE,       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sl, 0,                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(sl, 0,                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(sl,  0,                       LV_PART_MAIN | LV_STATE_DEFAULT);

    // Indicator (lime fill)
    lv_obj_set_style_bg_color(sl, lv_color_hex(TV_LIME),  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sl,   LV_OPA_COVER,           LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sl,   LV_RADIUS_CIRCLE,       LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(sl, 0,                    LV_PART_INDICATOR | LV_STATE_DEFAULT);

    // Knob: white circle, lime border
    lv_obj_set_style_bg_color(sl, lv_color_hex(0xFFFFFF),    LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(sl,   LV_OPA_COVER,              LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(sl,   LV_RADIUS_CIRCLE,          LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(sl, lv_color_hex(TV_LIME), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(sl, 3,                      LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(sl,   LV_OPA_COVER,          LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(sl,  10,                         LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(sl, 0,                     LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(sl, 0,                     LV_PART_KNOB | LV_STATE_DEFAULT);

    if(val_lbl) lv_obj_add_event_cb(sl, slider_pct_cb, LV_EVENT_VALUE_CHANGED, val_lbl);
    return sl;
}

// Bar helper (used inside flat tabs)
static lv_obj_t * mk_bar(lv_obj_t * p,
                          lv_coord_t x, lv_coord_t y, lv_coord_t w,
                          int value, uint32_t indicator_color)
{
    lv_obj_t * bar = lv_bar_create(p);
    lv_obj_set_size(bar, w, 12);
    lv_obj_set_pos(bar, x, y);
    lv_bar_set_range(bar, 0, 100);
    lv_bar_set_value(bar, value, LV_ANIM_OFF);
    lv_obj_set_style_bg_color(bar,  lv_color_hex(TV_TRACK),       LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(bar,    LV_OPA_COVER,                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(bar,    6,                             LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(bar, 0,                          LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(bar,  lv_color_hex(indicator_color), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(bar,    LV_OPA_COVER,                  LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(bar,    6,                             LV_PART_INDICATOR | LV_STATE_DEFAULT);
    return bar;
}

// Card container (rounded, dark bg, subtle lime border)
static lv_obj_t * mk_card(lv_obj_t * p, lv_coord_t y, lv_coord_t h)
{
    lv_obj_t * card = lv_obj_create(p);
    lv_obj_set_size(card, TAB_USE_W, h);
    lv_obj_set_pos(card, TAB_MARG, y);
    lv_obj_clear_flag(card, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(card,    lv_color_hex(TV_CARD),   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(card,      LV_OPA_COVER,            LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(card, lv_color_hex(TV_LIME),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(card, 1,                      LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(card,   LV_OPA_30,              LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(card,       12,                     LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(card,      CARD_PAD,               LV_PART_MAIN | LV_STATE_DEFAULT);
    return card;
}

// Bordered (outline-only) button used inside cards
static lv_obj_t * mk_outline_btn(lv_obj_t * p,
                                  lv_coord_t x, lv_coord_t y,
                                  lv_coord_t w, lv_coord_t h,
                                  const char * text, uint32_t color, lv_event_cb_t cb)
{
    lv_obj_t * btn = lv_btn_create(p);
    lv_obj_set_size(btn, w, h);
    lv_obj_set_pos(btn, x, y);
    lv_obj_set_style_bg_color(btn,    lv_color_hex(TV_CARD),  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(btn,      LV_OPA_COVER,           LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(btn,      LV_OPA_70,              LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_border_color(btn, lv_color_hex(color),   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(btn, 2,                     LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(btn,   LV_OPA_COVER,          LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(btn,       20,                    LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(btn, 0,                    LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(btn, 0,                    LV_PART_MAIN | LV_STATE_FOCUSED);
    lv_obj_set_style_shadow_width(btn,  0,                    LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * lbl = lv_label_create(btn);
    lv_label_set_text(lbl, text);
    lv_obj_set_style_text_color(lbl, lv_color_hex(color), 0);
    lv_obj_set_style_text_font(lbl,  &ui_font_name_14, 0);
    lv_obj_center(lbl);

    if(cb) lv_obj_add_event_cb(btn, cb, LV_EVENT_CLICKED, NULL);
    return btn;
}

static void _tab_set_date_cb(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    _ui_screen_change(&ui_date_picker, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0,
                      &ui_date_picker_screen_init);
}

static void _tab_set_time_cb(lv_event_t * e)
{
    if(lv_event_get_code(e) != LV_EVENT_CLICKED) return;
    _ui_screen_change(&ui_time_picker, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0,
                      &ui_time_picker_screen_init);
}

// ── Tab page builders ─────────────────────────────────────────────────────

static void build_tab_display(lv_obj_t * page)
{
    // Fixed layout — NO vertical scroll
    lv_obj_set_style_bg_opa(page,     LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(page,    0, 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_scroll_dir(page,       LV_DIR_NONE);

    // Title + divider
    mk_lbl(page, "DISPLAY", TAB_MARG, 2, TV_LIME, &ui_font_name_24);
    lv_obj_t * dsp_div = lv_obj_create(page);
    lv_obj_set_size(dsp_div, TAB_PG_W - 2*TAB_MARG, 1);
    lv_obj_set_pos(dsp_div, TAB_MARG, 32);
    lv_obj_set_style_bg_color(dsp_div,    lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(dsp_div,      LV_OPA_30, 0);
    lv_obj_set_style_border_width(dsp_div, 0, 0);
    lv_obj_set_style_radius(dsp_div,      0, 0);
    lv_obj_set_style_pad_all(dsp_div,     0, 0);

    // Section header
    mk_lbl(page, "BRIGHTNESS", TAB_MARG, 36, TV_MUTED, &ui_font_name_14);

    int cur_bright = sys_get_brightness();
    int cur_led    = sys_get_led();

    // ── Card 1: LCD Backlight (y=54, h=72) ──────────────────────────────
    // pad_bottom=0 → content 64px; slider y=36, knob_bottom=62 ✓
    lv_obj_t * c1 = mk_card(page, 54, 72);
    lv_obj_set_style_pad_bottom(c1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * lbl_bl_val = lv_label_create(c1);
    lv_label_set_text_fmt(lbl_bl_val, "%d%%", cur_bright);
    lv_obj_set_pos(lbl_bl_val, 0, 2);
    lv_obj_set_width(lbl_bl_val, CARD_INN);
    lv_obj_set_style_text_align(lbl_bl_val, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(lbl_bl_val, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_text_font(lbl_bl_val,  &ui_font_name_24, 0);

    mk_lbl(c1, "LCD Backlight", 0, 2, TV_TEXT, &ui_font_name_14);
    lv_obj_t * sl_bl = mk_display_slider(c1, 36, cur_bright, lbl_bl_val);
    lv_obj_add_event_cb(sl_bl, tab_bright_cb, LV_EVENT_VALUE_CHANGED, NULL);

    // ── Card 2: LED Indicator (y=132, h=72) ─────────────────────────────
    lv_obj_t * c2 = mk_card(page, 132, 72);
    lv_obj_set_style_pad_bottom(c2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * lbl_led_val = lv_label_create(c2);
    lv_label_set_text_fmt(lbl_led_val, "%d%%", cur_led);
    lv_obj_set_pos(lbl_led_val, 0, 2);
    lv_obj_set_width(lbl_led_val, CARD_INN);
    lv_obj_set_style_text_align(lbl_led_val, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(lbl_led_val, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_text_font(lbl_led_val,  &ui_font_name_24, 0);

    mk_lbl(c2, "LED Indicator", 0, 2, TV_TEXT, &ui_font_name_14);
    lv_obj_t * sl_led = mk_display_slider(c2, 36, cur_led, lbl_led_val);
    lv_obj_add_event_cb(sl_led, tab_led_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

static void build_tab_sound(lv_obj_t * page)
{
    lv_obj_set_style_bg_opa(page,      LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(page,     0, 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_scroll_dir(page,        LV_DIR_NONE);

    // Title
    mk_lbl(page, "SOUND", TAB_MARG, 6, TV_LIME, &ui_font_name_24);

    // Horizontal divider
    lv_obj_t * div = lv_obj_create(page);
    lv_obj_set_size(div, TAB_PG_W - 2*TAB_MARG, 1);
    lv_obj_set_pos(div, TAB_MARG, 34);
    lv_obj_set_style_bg_color(div,    lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(div,      LV_OPA_30, 0);
    lv_obj_set_style_border_width(div, 0, 0);
    lv_obj_set_style_radius(div,      0, 0);
    lv_obj_set_style_pad_all(div,     0, 0);

    // Section label
    mk_lbl(page, "AUDIO", TAB_MARG, 40, TV_MUTED, &ui_font_name_14);

    // ── Card 1: Speaker Volume ──────────────────────────────────────────
    // h=70 + pad_bottom=2  → content area 60 px; knob bottom lands at 58 px
    lv_obj_t * c1 = mk_card(page, 60, 70);
    lv_obj_set_style_pad_bottom(c1, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    int cur_vol = sys_get_volume();
    lv_obj_t * lbl_vol_val = lv_label_create(c1);
    lv_label_set_text_fmt(lbl_vol_val, "%d%%", cur_vol);
    lv_obj_set_pos(lbl_vol_val, 0, 2);
    lv_obj_set_width(lbl_vol_val, CARD_INN);
    lv_obj_set_style_text_align(lbl_vol_val, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(lbl_vol_val, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_text_font(lbl_vol_val, &ui_font_name_24, 0);

    mk_lbl(c1, "Speaker Volume", 0, 4, TV_TEXT, &ui_font_name_14);
    lv_obj_t * sl_vol = mk_display_slider(c1, 32, cur_vol, lbl_vol_val);
    lv_obj_add_event_cb(sl_vol, tab_vol_cb, LV_EVENT_VALUE_CHANGED, NULL);

    // ── Card 2: Key Tone ────────────────────────────────────────────────
    // h=66 → content area 50 px; subtitle bottom 48 px, switch bottom 41 px
    lv_obj_t * c2 = mk_card(page, 138, 66);

    mk_lbl(c2, "Key Tone", 0, 0, TV_TEXT, &ui_font_name_14);
    mk_lbl(c2, "tap beep", 0, 30, TV_MUTED, &ui_font_name_14);
    lv_obj_t * sw_key = mk_card_switch(c2, CARD_INN - 42, 14, sys_get_key_sound());
    lv_obj_add_event_cb(sw_key, tab_key_snd_cb, LV_EVENT_VALUE_CHANGED, NULL);
}

static void build_tab_connect(lv_obj_t * page)
{
    lv_obj_set_style_bg_opa(page,      LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(page,     0, 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_scroll_dir(page,        LV_DIR_NONE);

    mk_lbl(page, "CONNECT", TAB_MARG, 6, TV_LIME, &ui_font_name_24);

    lv_obj_t * con_div = lv_obj_create(page);
    lv_obj_set_size(con_div, TAB_PG_W - 2*TAB_MARG, 1);
    lv_obj_set_pos(con_div, TAB_MARG, 34);
    lv_obj_set_style_bg_color(con_div,    lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(con_div,      LV_OPA_30, 0);
    lv_obj_set_style_border_width(con_div, 0, 0);
    lv_obj_set_style_radius(con_div,      0, 0);
    lv_obj_set_style_pad_all(con_div,     0, 0);

    mk_lbl(page, "Bluetooth", TAB_MARG, 40, TV_MUTED, &ui_font_name_14);
    lv_obj_t * sw_ble = mk_switch(page, 35, settings_get_ble_en());
    lv_obj_add_event_cb(sw_ble, tab_ble_sw_cb, LV_EVENT_VALUE_CHANGED, NULL);

    mk_lbl(page, "Wi-Fi", TAB_MARG, 78, TV_MUTED, &ui_font_name_14);
    lv_obj_t * sw_wifi = mk_switch(page, 73, settings_get_wifi_en());
    lv_obj_add_event_cb(sw_wifi, tab_wifi_sw_cb, LV_EVENT_VALUE_CHANGED, NULL);

    /* Show saved SSID from NVS; status reflects live connection state */
    char saved_ssid[33] = {};
    persist_get_str(PKEY_WIFI_SSID, saved_ssid, sizeof(saved_ssid), "");
    bool wifi_on = ui_wifi_bridge_is_connected();
    mk_lbl(page, "SSID", TAB_MARG, 114, TV_MUTED, &ui_font_name_14);
    mk_lbl(page, saved_ssid[0] ? saved_ssid : "---", TAB_MARG, 130, TV_TEXT, &ui_font_name_14);
    mk_lbl_r(page, wifi_on ? "Connected" : "Not connected", 130,
             wifi_on ? TV_LIME : TV_MUTED, &ui_font_name_14);
}

static void build_tab_time(lv_obj_t * page)
{
    lv_obj_set_style_bg_opa(page,      LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(page,     0, 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_scroll_dir(page,        LV_DIR_NONE);

    mk_lbl(page, "TIME", TAB_MARG, 6, TV_LIME, &ui_font_name_24);

    lv_obj_t * tim_div = lv_obj_create(page);
    lv_obj_set_size(tim_div, TAB_PG_W - 2*TAB_MARG, 1);
    lv_obj_set_pos(tim_div, TAB_MARG, 34);
    lv_obj_set_style_bg_color(tim_div,    lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(tim_div,      LV_OPA_30, 0);
    lv_obj_set_style_border_width(tim_div, 0, 0);
    lv_obj_set_style_radius(tim_div,      0, 0);
    lv_obj_set_style_pad_all(tim_div,     0, 0);

    mk_lbl(page, "Date", TAB_MARG, 40, TV_MUTED, &ui_font_name_14);
    s_lbl_date = mk_lbl(page, "--/--/----", TAB_MARG, 60, TV_TEXT, &ui_font_name_24);

    mk_lbl(page, "Time", TAB_MARG, 110, TV_MUTED, &ui_font_name_14);
    s_lbl_time_str = mk_lbl(page, "--- --:--", TAB_MARG, 130, TV_TEXT, &ui_font_name_24);

    mk_outline_btn(page, TAB_MARG,           170, 108, 30, "Set Date", TV_LIME,  _tab_set_date_cb);
    mk_outline_btn(page, TAB_MARG + 114,     170, 108, 30, "Set Time", TV_MUTED, _tab_set_time_cb);

    tab_time_refresh(NULL);

    if(!s_time_timer) {
        s_time_timer = lv_timer_create(tab_time_refresh, 1000, NULL);
    }
}

static void build_tab_system(lv_obj_t * page)
{
    // Page itself is NOT scrollable — title stays fixed
    lv_obj_set_style_bg_opa(page,      LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(page,     0, 0);
    lv_obj_set_style_border_width(page, 0, 0);
    lv_obj_set_scroll_dir(page,        LV_DIR_NONE);

    // ── Fixed header: title + divider ────────────────────────────────────────
    mk_lbl(page, "SYSTEM", TAB_MARG, 4, TV_LIME, &ui_font_name_24);
    lv_obj_t * sys_div = lv_obj_create(page);
    lv_obj_set_size(sys_div, TAB_PG_W - 2*TAB_MARG, 1);
    lv_obj_set_pos(sys_div, TAB_MARG, 34);
    lv_obj_set_style_bg_color(sys_div, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(sys_div,   LV_OPA_30, 0);
    lv_obj_set_style_border_width(sys_div, 0, 0);
    lv_obj_set_style_radius(sys_div,   0, 0);
    lv_obj_set_style_pad_all(sys_div,  0, 0);

    // ── Scrollable content sub-container (below header) ──────────────────────
    lv_obj_t * sc = lv_obj_create(page);
    lv_obj_set_size(sc, TAB_PG_W, 241 - 38);
    lv_obj_set_pos(sc, 0, 38);
    lv_obj_set_scroll_dir(sc, LV_DIR_VER);
    lv_obj_set_scrollbar_mode(sc, LV_SCROLLBAR_MODE_AUTO);
    lv_obj_set_style_bg_opa(sc,        LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(sc,       0, 0);
    lv_obj_set_style_pad_bottom(sc,    40, 0);
    lv_obj_set_style_border_width(sc,  0, 0);
    lv_obj_set_style_radius(sc,        0, 0);

    int y = 4;

    // ── POWER ────────────────────────────────────────────────────────────────
    mk_lbl(sc, "POWER", TAB_MARG, y, TV_MUTED, &ui_font_name_14);
    y += 20;

    lv_obj_t * c_bat = mk_card(sc, y, 70);
    mk_lbl(c_bat, "Battery", 0, 0, TV_TEXT, &ui_font_name_14);
    s_sys_bat_status = mk_lbl(c_bat, "discharging", 0, 18, TV_MUTED, &ui_font_name_14);

    s_sys_bat_pct_lbl = lv_label_create(c_bat);
    lv_label_set_text(s_sys_bat_pct_lbl, "--");
    lv_obj_set_pos(s_sys_bat_pct_lbl, 0, 0);
    lv_obj_set_width(s_sys_bat_pct_lbl, CARD_INN);
    lv_obj_set_style_text_align(s_sys_bat_pct_lbl, LV_TEXT_ALIGN_RIGHT, 0);
    lv_obj_set_style_text_color(s_sys_bat_pct_lbl, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_text_font(s_sys_bat_pct_lbl, &ui_font_name_24, 0);

    lv_obj_t * bat_body = lv_obj_create(c_bat);
    lv_obj_set_size(bat_body, 44, 22);
    lv_obj_set_pos(bat_body, CARD_INN - 52, 28);
    lv_obj_clear_flag(bat_body, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(bat_body, lv_color_hex(TV_CARD), 0);
    lv_obj_set_style_bg_opa(bat_body, LV_OPA_COVER, 0);
    lv_obj_set_style_border_color(bat_body, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_border_width(bat_body, 2, 0);
    lv_obj_set_style_radius(bat_body, 4, 0);
    lv_obj_set_style_pad_all(bat_body, 0, 0);
    // bat_fill as sibling on c_bat, manually positioned 4px inside bat_body border
    s_sys_bat_fill = lv_obj_create(c_bat);
    lv_obj_set_size(s_sys_bat_fill, 36, 14);   /* initial 100%; _sys_bat_refresh updates width */
    lv_obj_set_pos(s_sys_bat_fill, CARD_INN - 52 + 4, 32);
    lv_obj_clear_flag(s_sys_bat_fill, LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_set_style_bg_color(s_sys_bat_fill, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(s_sys_bat_fill, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(s_sys_bat_fill, 0, 0);
    lv_obj_set_style_radius(s_sys_bat_fill, 2, 0);
    lv_obj_set_style_pad_all(s_sys_bat_fill, 0, 0);
    lv_obj_set_style_shadow_width(s_sys_bat_fill, 0, 0);
    lv_obj_set_style_outline_width(s_sys_bat_fill, 0, 0);
    lv_obj_t * bat_nub = lv_obj_create(c_bat);
    lv_obj_set_size(bat_nub, 6, 10);
    lv_obj_set_pos(bat_nub, CARD_INN - 52 + 45, 34);
    lv_obj_clear_flag(bat_nub, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(bat_nub, lv_color_hex(TV_LIME), 0);
    lv_obj_set_style_bg_opa(bat_nub, LV_OPA_COVER, 0);
    lv_obj_set_style_border_width(bat_nub, 0, 0);
    lv_obj_set_style_radius(bat_nub, 2, 0);
    lv_obj_set_style_pad_all(bat_nub, 0, 0);

    /* Prime display with real battery data, then refresh every second */
    _sys_bat_refresh(NULL);
    if (!s_sys_bat_timer) {
        s_sys_bat_timer = lv_timer_create(_sys_bat_refresh, 1000, NULL);
    }
    y += 70 + 8;

    lv_obj_t * c_rb = mk_card(sc, y, 66);
    mk_lbl(c_rb, "Reboot", 0, 0, TV_TEXT, &ui_font_name_14);
    mk_lbl(c_rb, "soft restart", 0, 30, TV_MUTED, &ui_font_name_14);
    mk_outline_btn(c_rb, CARD_INN - 90, 7, 90, 36, "Reboot", 0xBEE700, tab_reboot_cb);
    y += 66 + 8;

    // ── STORAGE ──────────────────────────────────────────────────────────────
    mk_lbl(sc, "STORAGE", TAB_MARG, y, TV_MUTED, &ui_font_name_14);
    y += 20;

    {
        uint64_t sd_total = (uint64_t)ui_sd_total_bytes();
        uint64_t sd_used  = (uint64_t)ui_sd_used_bytes();
        int sd_pct = (sd_total > 0) ? (int)((sd_used * 100ULL) / sd_total) : 0;
        char sd_info[40];
        if(sd_total == 0) {
            lv_snprintf(sd_info, sizeof(sd_info), "not mounted");
        } else {
            uint32_t u_mb = (uint32_t)(sd_used  / 1048576UL);
            uint32_t t_mb = (uint32_t)(sd_total / 1048576UL);
            if(t_mb >= 1024)
                lv_snprintf(sd_info, sizeof(sd_info), "%u.%u / %u.%u GB",
                            u_mb / 1024, (u_mb % 1024) * 10 / 1024,
                            t_mb / 1024, (t_mb % 1024) * 10 / 1024);
            else
                lv_snprintf(sd_info, sizeof(sd_info), "%u / %u MB", u_mb, t_mb);
        }

        lv_obj_t * c_sd = mk_card(sc, y, 68);
        mk_lbl(c_sd, "SD Card", 0, 0, TV_TEXT, &ui_font_name_14);
        mk_bar(c_sd, 0, 20, CARD_INN, sd_pct, TV_ORANGE);
        {
            lv_obj_t * l = lv_label_create(c_sd);
            lv_label_set_text(l, sd_info);
            lv_obj_set_pos(l, 0, 38);
            lv_obj_set_width(l, CARD_INN);
            lv_obj_set_style_text_align(l, LV_TEXT_ALIGN_RIGHT, 0);
            lv_obj_set_style_text_color(l, lv_color_hex(TV_MUTED), 0);
            lv_obj_set_style_text_font(l, &ui_font_name_14, 0);
        }
        y += 68 + 8;
    }

    // ── FLASH / NVS ──────────────────────────────────────────────────────────
    mk_lbl(sc, "FLASH", TAB_MARG, y, TV_MUTED, &ui_font_name_14);
    y += 20;

    {
        nvs_stats_t nst = {};
        nvs_get_stats(NULL, &nst);   /* NULL = default NVS partition */
        int nvs_pct = (nst.total_entries > 0)
                      ? (int)((nst.used_entries * 100u) / nst.total_entries) : 0;
        char nvs_info[40];
        lv_snprintf(nvs_info, sizeof(nvs_info), "%u / %u entries",
                    (unsigned)nst.used_entries, (unsigned)nst.total_entries);

        lv_obj_t * c_nvs = mk_card(sc, y, 68);
        mk_lbl(c_nvs, "NVS Config", 0, 0, TV_TEXT, &ui_font_name_14);
        mk_bar(c_nvs, 0, 20, CARD_INN, nvs_pct, TV_LIME);
        {
            lv_obj_t * l = lv_label_create(c_nvs);
            lv_label_set_text(l, nvs_info);
            lv_obj_set_pos(l, 0, 38);
            lv_obj_set_width(l, CARD_INN);
            lv_obj_set_style_text_align(l, LV_TEXT_ALIGN_RIGHT, 0);
            lv_obj_set_style_text_color(l, lv_color_hex(TV_MUTED), 0);
            lv_obj_set_style_text_font(l, &ui_font_name_14, 0);
        }
        y += 68 + 8;
    }

    // ── MAINTENANCE ──────────────────────────────────────────────────────────
    mk_lbl(sc, "MAINTENANCE", TAB_MARG, y, TV_MUTED, &ui_font_name_14);
    y += 20;

    lv_obj_t * c_fr = mk_card(sc, y, 84);
    mk_lbl(c_fr, "Factory Reset", 0, 0, TV_TEXT, &ui_font_name_14);
    mk_lbl(c_fr, "erase all", 0, 30, TV_MUTED, &ui_font_name_14);
    mk_lbl(c_fr, "settings", 0, 48, TV_MUTED, &ui_font_name_14);
    mk_outline_btn(c_fr, CARD_INN - 90, 10, 90, 44, "Reset", TV_DANGER, tab_factory_reset_cb);
    y += 84 + 8;

}

// ── Screen init / destroy ─────────────────────────────────────────────────

void ui_tabview_screen_init(void)
{
    ui_tabview = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_tabview, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_color(ui_tabview, lv_color_hex(TV_BG), 0);
    lv_obj_set_style_bg_opa(ui_tabview, LV_OPA_COVER, 0);
    lv_obj_set_style_shadow_width(ui_tabview, 0, 0);
    lv_obj_set_style_outline_width(ui_tabview, 0, 0);

    // ── Background image ─────────────────────────────────────────────────
    lv_obj_t * tv_bg = lv_img_create(ui_tabview);
    lv_img_set_src(tv_bg, &ui_img_background_v_png);
    lv_obj_set_width(tv_bg, LV_SIZE_CONTENT);
    lv_obj_set_height(tv_bg, LV_SIZE_CONTENT);
    lv_obj_set_align(tv_bg, LV_ALIGN_CENTER);
    lv_obj_add_flag(tv_bg, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(tv_bg, LV_OBJ_FLAG_SCROLLABLE);

    // ── Tabview ───────────────────────────────────────────────────────────
    ui_tabview_settings = lv_tabview_create(ui_tabview, LV_DIR_LEFT, TAB_BAR_W);
    lv_obj_set_size(ui_tabview_settings, 320, 241);
    lv_obj_set_pos(ui_tabview_settings, 0, -1);
    lv_obj_clear_flag(ui_tabview_settings, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_set_style_bg_opa(ui_tabview_settings, LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(ui_tabview_settings, 0, 0);
    lv_obj_set_style_border_width(ui_tabview_settings, 0, 0);
    lv_obj_set_style_shadow_width(ui_tabview_settings, 0, 0);
    lv_obj_set_style_outline_width(ui_tabview_settings, 0, 0);

    lv_obj_t * cont = lv_tabview_get_content(ui_tabview_settings);
    lv_obj_set_style_bg_opa(cont, LV_OPA_TRANSP, 0);
    lv_obj_set_style_pad_all(cont, 0, 0);

    // ── Tab button bar styling ────────────────────────────────────────────
    lv_obj_t * tab_btns = lv_tabview_get_tab_btns(ui_tabview_settings);

    lv_obj_set_style_bg_opa(tab_btns,    LV_OPA_TRANSP,          LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(tab_btns, 0,                   LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_side(tab_btns,  LV_BORDER_SIDE_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_all(tab_btns,   0,                      LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_opa(tab_btns,    LV_OPA_TRANSP,          LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_color(tab_btns, lv_color_hex(TV_MUTED), LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(tab_btns, &ui_font_name_14,        LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(tab_btns, 0,                   LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(tab_btns, 0,                   LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(tab_btns, 0,                  LV_PART_ITEMS | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(tab_btns,  lv_color_hex(TV_LIME),  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(tab_btns,    LV_OPA_COVER,           LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_text_color(tab_btns, lv_color_hex(TV_INK),  LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_radius(tab_btns,    8,                       LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_border_width(tab_btns, 0,                   LV_PART_ITEMS | LV_STATE_CHECKED);
    lv_obj_set_style_shadow_width(tab_btns, 0,                     LV_PART_ITEMS | LV_STATE_CHECKED);

    // ── Add tabs + build content ──────────────────────────────────────────
    ui_TabPage1 = lv_tabview_add_tab(ui_tabview_settings, "Display");
    ui_TabPage2 = lv_tabview_add_tab(ui_tabview_settings, "Sound");
    ui_TabPage3 = lv_tabview_add_tab(ui_tabview_settings, "Connect");
    ui_TabPage4 = lv_tabview_add_tab(ui_tabview_settings, "Time");
    ui_TabPage5 = lv_tabview_add_tab(ui_tabview_settings, "System");

    build_tab_display(ui_TabPage1);
    build_tab_sound(ui_TabPage2);
    build_tab_connect(ui_TabPage3);
    build_tab_time(ui_TabPage4);
    build_tab_system(ui_TabPage5);

    // ── Bottom key bar ────────────────────────────────────────────────────
    ui_tab_key_prompts_bg = lv_img_create(ui_tabview);
    lv_img_set_src(ui_tab_key_prompts_bg, &ui_img_key_prompts_bg_png);
    lv_obj_set_width(ui_tab_key_prompts_bg,  LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tab_key_prompts_bg, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_tab_key_prompts_bg, 168, 204);
    lv_obj_add_flag(ui_tab_key_prompts_bg, LV_OBJ_FLAG_ADV_HITTEST);
    lv_obj_clear_flag(ui_tab_key_prompts_bg, LV_OBJ_FLAG_SCROLLABLE);

    ui_tab_key_a_bg = lv_img_create(ui_tabview);
    lv_img_set_src(ui_tab_key_a_bg, &ui_img_key_a_png);
    lv_obj_set_width(ui_tab_key_a_bg,  LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tab_key_a_bg, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_tab_key_a_bg, 171, 207);
    lv_obj_add_flag(ui_tab_key_a_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_tab_key_a_bg, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_tab_key_a_bg, tab_key_a_cb, LV_EVENT_CLICKED, NULL);

    ui_tab_key_b_bg = lv_img_create(ui_tabview);
    lv_img_set_src(ui_tab_key_b_bg, &ui_img_key_b_png);
    lv_obj_set_width(ui_tab_key_b_bg,  LV_SIZE_CONTENT);
    lv_obj_set_height(ui_tab_key_b_bg, LV_SIZE_CONTENT);
    lv_obj_set_pos(ui_tab_key_b_bg, 241, 207);
    lv_obj_add_flag(ui_tab_key_b_bg, LV_OBJ_FLAG_ADV_HITTEST | LV_OBJ_FLAG_CLICKABLE);
    lv_obj_clear_flag(ui_tab_key_b_bg, LV_OBJ_FLAG_SCROLLABLE);
    lv_obj_add_event_cb(ui_tab_key_b_bg, tab_key_b_cb, LV_EVENT_CLICKED, NULL);

    ui_tab_key_a_save = lv_label_create(ui_tabview);
    lv_obj_set_pos(ui_tab_key_a_save, 194, 211);
    lv_label_set_text(ui_tab_key_a_save, "Home");
    lv_obj_set_style_text_color(ui_tab_key_a_save, lv_color_hex(0x000000), 0);
    lv_obj_set_style_text_font(ui_tab_key_a_save,  &ui_font_name_14, 0);

    ui_tab_key_a_back = lv_label_create(ui_tabview);
    lv_obj_set_pos(ui_tab_key_a_back, 265, 211);
    lv_label_set_text(ui_tab_key_a_back, "Back");
    lv_obj_set_style_text_color(ui_tab_key_a_back, lv_color_hex(0x000000), 0);
    lv_obj_set_style_text_font(ui_tab_key_a_back,  &ui_font_name_14, 0);
}

void ui_tabview_screen_destroy(void)
{
    if(s_time_timer)    { lv_timer_del(s_time_timer);    s_time_timer    = NULL; }
    if(s_sys_bat_timer) { lv_timer_del(s_sys_bat_timer); s_sys_bat_timer = NULL; }
    s_lbl_date        = NULL;
    s_lbl_time_str    = NULL;
    s_sys_bat_pct_lbl = NULL;
    s_sys_bat_status  = NULL;
    s_sys_bat_fill    = NULL;

    if(ui_tabview) lv_obj_del(ui_tabview);

    ui_tabview            = NULL;
    ui_tabview_settings   = NULL;
    ui_TabPage1           = NULL;
    ui_TabPage2           = NULL;
    ui_TabPage3           = NULL;
    ui_TabPage4           = NULL;
    ui_TabPage5           = NULL;
    ui_tab_key_prompts_bg = NULL;
    ui_tab_key_a_bg       = NULL;
    ui_tab_key_b_bg       = NULL;
    ui_tab_key_a_save     = NULL;
    ui_tab_key_a_back     = NULL;
}
